-- CREATE A DATABASE, IF IT DOES NOT EXIST ALREADY
CREATE DATABASE IF NOT EXISTS mcsp02donuts;
-- CONNECT TO THE DATABASE

USE mcsp02donuts;

-- CREATE A DONUTS TABLE
-- WITH COLUMNS
CREATE TABLE IF NOT EXISTS donuts(
    donut_id INT PRIMARY KEY AUTO_INCREMENT, 
    filling VARCHAR(25), 
    stale TINYINT(1)
);
    
